In [1]:
import pandas as pd
import numpy as np

#Importer les fichiers
df_all = pd.read_csv("world-happiness-report.csv")
pd.set_option("display.max_columns", None) #Pour afficher toutes les colonnes

df_2021 = pd.read_csv("world-happiness-report-2021.csv")
pd.set_option("display.max_columns", None) #Pour afficher toutes les colonnes


#Visualiser les fichiers
display(df_all.head())
display(df_2021.head())

#Dimension 
print("Il y a", len(df_all["Country name"].unique()), "pays différents dans df_all")
print("Il y a", len(df_2021["Country name"].unique()), "pays différents dans df_2021")
df_all.isna().sum()*100/len(df_all)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

Il y a 166 pays différents dans df_all
Il y a 149 pays différents dans df_2021

Country name                        0.000000
year                                0.000000
Life Ladder                         0.000000
Log GDP per capita                  1.847101
Social support                      0.667009
Healthy life expectancy at birth    2.821960
Freedom to make life choices        1.641868
Generosity                          4.566444
Perceptions of corruption           5.643920
Positive affect                     1.128784
Negative affect                     0.820934
dtype: float64

In [2]:
#Renomer les colonnes pour df_all
df_all.rename(columns={'Country name': 'Country', 
                    'Regional indicator': 'Region', 
                    'Life Ladder': 'Ladder_score',
                   "Log GDP per capita" : "PIB_habitant",
                   "year":"Year",
                   "Healthy life expectancy at birth" : "Healthy life expectancy",
                   "Freedom to make life choices" : "Freedom",
                   "Perceptions of corruption" : "Corruption"}, inplace=True)

df_all.columns = df_all.columns.str.replace(" ", "_")



#Renomer les colonnes pour df_all df_2021
df_2021.rename(columns={'Country name': 'Country', 
                    'Regional indicator': 'Region', 
                    'Ladder score': 'Ladder_score',
                   "Logged GDP per capita" : "PIB_habitant",
                   "Freedom to make life choices" : "Freedom",
                   "Perceptions of corruption" : "Corruption",
                   "Explained by: Log GDP per capita" : "Explained_by_PIB",
                   "Explained by: Social support" : "Explained by Social support",
                   "Explained by: Healthy life expectancy" : "Explained by Healthy life expectancy",
                   "Explained by: Freedom to make life choices" : "Explained by Freedom",
                   "Explained by: Generosity" : "Explained by Generosity",
                   "Explained by: Perceptions of corruption" : "Explained by corruption"}, inplace=True)

df_2021.columns = df_2021.columns.str.replace(" ", "_")


display(df_all.head())
display(df_2021.head())

,Country,Year,Ladder_score,PIB_habitant,Social_support,Healthy_life_expectancy,Freedom,Generosity,Corruption,Positive_affect,Negative_affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

,Country,Region,Ladder_score,Standard_error_of_ladder_score,upperwhisker,lowerwhisker,PIB_habitant,Social_support,Healthy_life_expectancy,Freedom,Generosity,Corruption,Ladder_score_in_Dystopia,Explained_by_PIB,Explained_by_Social_support,Explained_by_Healthy_life_expectancy,Explained_by_Freedom,Explained_by_Generosity,Explained_by_corruption,Dystopia_+_residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

In [3]:
#Suppression des colonnes inutiles

df_2021 = df_2021.drop(["Standard_error_of_ladder_score", "upperwhisker", "lowerwhisker",
                       "Ladder_score_in_Dystopia", "Explained_by_PIB", "Explained_by_Social_support",
                        "Explained_by_Healthy_life_expectancy", "Explained_by_Freedom", "Explained_by_Generosity",
                        "Explained_by_corruption", "Dystopia_+_residual"], axis = 1)

In [4]:
display(df_all.head())
display(df_2021.head())


print("Nous avons", df_all.Year.isna().sum(), "valeur(s) manquante(s) dans Year") #Pas de valeur manquante ds Year

,Country,Year,Ladder_score,PIB_habitant,Social_support,Healthy_life_expectancy,Freedom,Generosity,Corruption,Positive_affect,Negative_affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

,Country,Region,Ladder_score,PIB_habitant,Social_support,Healthy_life_expectancy,Freedom,Generosity,Corruption
0,Finland,Western Europe,7.842,10.775,0.954,72.0,0.949,-0.098,0.186
1,Denmark,Western Europe,7.620,10.933,0.954,72.7,0.946,0.030,0.179
2,Switzerland,Western Europe,7.571,11.117,0.942,74.4,0.919,0.025,0.292
3,Iceland,Western Europe,7.554,10.878,0.983,73.0,0.955,0.160,0.673
4,Netherlands,Western Europe,7.464,10.932,0.942,72.4,0.913,0.175,0.338

Nous avons 0 valeur(s) manquante(s) dans Year

In [5]:
#Merge des 2 fichiers pour avoir les régions pour tous les pays

df_merge = pd.merge(df_all, df_2021, on = "Country", how = "outer")

df_merge.head()

,Country,Year,Ladder_score_x,PIB_habitant_x,Social_support_x,Healthy_life_expectancy_x,Freedom_x,Generosity_x,Corruption_x,Positive_affect,Negative_affect,Region,Ladder_score_y,PIB_habitant_y,Social_support_y,Healthy_life_expectancy_y,Freedom_y,Generosity_y,Corruption_y
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924

In [6]:
#Visualisation de la dimension des fichiers

print(df_all.shape)
print(df_merge.shape)

#On voit qu'il y a seulement 1949 lignes, il nous en manque donc des lignes

(1949, 11)
(1949, 19)

In [7]:
#Concaténation de df_merge et df_2021

df_final = pd.concat([df_merge, df_2021], ignore_index=True, axis = 0)


#Tri pour vérifier que Afghanistan 2021 a bien été ajouté
df_final = df_final.sort_values(by = ["Country", "Year"]) 


print(df_final.shape) #Les lignes on bien étaient rajoutées mais trop de colonnes

df_final = df_final.reset_index(drop = True)

df_final.head(13) #Pour avoir un visuel sur le Afghanistan 2021

(2098, 26)

,Country,Year,Ladder_score_x,PIB_habitant_x,Social_support_x,Healthy_life_expectancy_x,Freedom_x,Generosity_x,Corruption_x,Positive_affect,Negative_affect,Region,Ladder_score_y,PIB_habitant_y,Social_support_y,Healthy_life_expectancy_y,Freedom_y,Generosity_y,Corruption_y,Ladder_score,PIB_habitant,Social_support,Healthy_life_expectancy,Freedom,Generosity,Corruption
0,Afghanistan,2008.0,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,2009.0,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,2010.0,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,2011.0,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,2012.0,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Afghanistan,2013.0,3.572,7.725,0.484,52.56,0.578,0.061,0.823,0.621,0.273,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Afghanistan,2014.0,3.131,7.718,0.526,52.88,0.509,0.104,0.871,0.532,0.375,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Afghanistan,2015.0,3.983,7.702,0.529,53.20,0.389,0.080,0.881,0.554,0.339,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Afghanistan,2016.0,4.220,7.697,0.559,53.00,0.523,0.042,0.793,0.565,0.348,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Afghanistan,2017.0,2.662,7.697,0.491,52.80,0.427,-0.121,0.954,0.496,0.371,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Afghanistan,2018.0,2.694,7.692,0.508,52.60,0.374,-0.094,0.928,0.424,0.405,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Afghanistan,2019.0,2.375,7.697,0.420,52.40,0.394,-0.108,0.924,0.351,0.502,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,South Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.523,7.695,0.463,52.493,0.382,-0.102,0.924

In [8]:
#On remet les données de 2021 à la bonne place

df_final["Year"].fillna(2021, inplace = True) #Ajout de 2021 au NaN de Year 
df_final["Year"]= df_final["Year"].astype("int") #Year au format int


df_final["Ladder_score_x"].fillna(df_final["Ladder_score"], inplace= True)
df_final["PIB_habitant_x"].fillna(df_final["PIB_habitant"], inplace= True)
df_final["Social_support_x"].fillna(df_final["Social_support"], inplace= True)
df_final["Healthy_life_expectancy_x"].fillna(df_final["Healthy_life_expectancy"], inplace= True)
df_final["Freedom_x"].fillna(df_final["Freedom"], inplace= True)
df_final["Generosity_x"].fillna(df_final["Generosity"], inplace= True)
df_final["Corruption_x"].fillna(df_final["Corruption"], inplace= True)

df_final.head(13) #Pour avoir un visuel sur le Afghanistan 2021. Si on enlève .head(13), on a visuel sur Zimbabwe

,Country,Year,Ladder_score_x,PIB_habitant_x,Social_support_x,Healthy_life_expectancy_x,Freedom_x,Generosity_x,Corruption_x,Positive_affect,Negative_affect,Region,Ladder_score_y,PIB_habitant_y,Social_support_y,Healthy_life_expectancy_y,Freedom_y,Generosity_y,Corruption_y,Ladder_score,PIB_habitant,Social_support,Healthy_life_expectancy,Freedom,Generosity,Corruption
0,Afghanistan,2008,3.724,7.370,0.451,50.800,0.718,0.168,0.882,0.518,0.258,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,2009,4.402,7.540,0.552,51.200,0.679,0.190,0.850,0.584,0.237,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,2010,4.758,7.647,0.539,51.600,0.600,0.121,0.707,0.618,0.275,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,2011,3.832,7.620,0.521,51.920,0.496,0.162,0.731,0.611,0.267,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,2012,3.783,7.705,0.521,52.240,0.531,0.236,0.776,0.710,0.268,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Afghanistan,2013,3.572,7.725,0.484,52.560,0.578,0.061,0.823,0.621,0.273,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Afghanistan,2014,3.131,7.718,0.526,52.880,0.509,0.104,0.871,0.532,0.375,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Afghanistan,2015,3.983,7.702,0.529,53.200,0.389,0.080,0.881,0.554,0.339,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Afghanistan,2016,4.220,7.697,0.559,53.000,0.523,0.042,0.793,0.565,0.348,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Afghanistan,2017,2.662,7.697,0.491,52.800,0.427,-0.121,0.954,0.496,0.371,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Afghanistan,2018,2.694,7.692,0.508,52.600,0.374,-0.094,0.928,0.424,0.405,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Afghanistan,2019,2.375,7.697,0.420,52.400,0.394,-0.108,0.924,0.351,0.502,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Afghanistan,2021,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,NaN,NaN,South Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.523,7.695,0.463,52.493,0.382,-0.102,0.924

In [9]:
#Suppression des colonnes inutiles

df_final.drop(df_final.columns[-14:], axis = 1, inplace = True) #Suppression des 14 dernières colonnes
                                                            #A partir de Ladder_score_y

df_final.head()

,Country,Year,Ladder_score_x,PIB_habitant_x,Social_support_x,Healthy_life_expectancy_x,Freedom_x,Generosity_x,Corruption_x,Positive_affect,Negative_affect,Region
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258,South Asia
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237,South Asia
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275,South Asia
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267,South Asia
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268,South Asia

In [10]:
#On mets les noms des colonnes au propre

df_final.columns = df_final.columns.str.replace("_x", "")


df_final.head()

,Country,Year,Ladder_score,PIB_habitant,Social_support,Healthy_life_expectancy,Freedom,Generosity,Corruption,Positive_affect,Negative_affect,Region
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258,South Asia
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237,South Asia
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275,South Asia
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267,South Asia
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268,South Asia

In [11]:
#Taux de valeurs manquantes (Modifier chacun de son coté les NaN pour le ML)

(df_final.isna().sum())*100/len(df_final)

Country                    0.000000
Year                       0.000000
Ladder_score               0.000000
PIB_habitant               1.715920
Social_support             0.619638
Healthy_life_expectancy    2.621544
Freedom                    1.525262
Generosity                 4.242135
Corruption                 5.243089
Positive_affect            8.150620
Negative_affect            7.864633
Region                     3.002860
dtype: float64

In [12]:
#Suppression des Région NaN

df_final.dropna(subset = "Region", inplace = True)

(df_final.isna().sum())*100/len(df_final)

Country                    0.000000
Year                       0.000000
Ladder_score               0.000000
PIB_habitant               1.179361
Social_support             0.442260
Healthy_life_expectancy    2.506143
Freedom                    1.474201
Generosity                 3.734644
Corruption                 5.110565
Positive_affect            8.206388
Negative_affect            7.960688
Region                     0.000000
dtype: float64

In [13]:
df_final["Positive_affect"].fillna(method = "pad", inplace = True) #Par la valeur juste avant
df_final["Negative_affect"].fillna(method = "pad", inplace = True) #Par la valeur juste avant

df_final.fillna(method = "bfill", inplace = True) #Par la valeur juste après

print(df_final.isna().sum())

Country                    0
Year                       0
Ladder_score               0
PIB_habitant               0
Social_support             0
Healthy_life_expectancy    0
Freedom                    0
Generosity                 0
Corruption                 0
Positive_affect            0
Negative_affect            0
Region                     0
dtype: int64

In [14]:
# Supprimer la colonne 'Country'
df_final = df_final.drop(['Country', 'Year'], axis=1)

# Utiliser get_dummies pour encoder la colonne 'Region'
df_final = pd.get_dummies(df_final, columns=['Region'])

# Afficher le DataFrame résultant
df_final.head()

,Ladder_score,PIB_habitant,Social_support,Healthy_life_expectancy,Freedom,Generosity,Corruption,Positive_affect,Negative_affect,Region_Central and Eastern Europe,Region_Commonwealth of Independent States,Region_East Asia,Region_Latin America and Caribbean,Region_Middle East and North Africa,Region_North America and ANZ,Region_South Asia,Region_Southeast Asia,Region_Sub-Saharan Africa,Region_Western Europe
0,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258,False,False,False,False,False,False,True,False,False,False
1,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237,False,False,False,False,False,False,True,False,False,False
2,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275,False,False,False,False,False,False,True,False,False,False
3,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267,False,False,False,False,False,False,True,False,False,False
4,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268,False,False,False,False,False,False,True,False,False,False

In [15]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2035 entries, 0 to 2097
Data columns (total 19 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Ladder_score                               2035 non-null   float64
 1   PIB_habitant                               2035 non-null   float64
 2   Social_support                             2035 non-null   float64
 3   Healthy_life_expectancy                    2035 non-null   float64
 4   Freedom                                    2035 non-null   float64
 5   Generosity                                 2035 non-null   float64
 6   Corruption                                 2035 non-null   float64
 7   Positive_affect                            2035 non-null   float64
 8   Negative_affect                            2035 non-null   float64
 9   Region_Central and Eastern Europe          2035 non-null   bool
 10  Region_Commonwealth of Independent States  2035 non-null   bool
 11  Region_East Asia                           2035 non-null   bool
 12  Region_Latin America and Caribbean         2035 non-null   bool
 13  Region_Middle East and North Africa        2035 non-null   bool
 14  Region_North America and ANZ               2035 non-null   bool
 15  Region_South Asia                          2035 non-null   bool
 16  Region_Southeast Asia                      2035 non-null   bool
 17  Region_Sub-Saharan Africa                  2035 non-null   bool
 18  Region_Western Europe                      2035 non-null   bool
dtypes: bool(10), float64(9)
memory usage: 178.9 KB

In [16]:
#Exporter le fichier au format CSV

#from pathlib import Path

#filepath = Path('/Users/bapt/Downloads/World_happiness_ML.csv') #Nom du chemin à suivre pour enregistrer
#filepath.parent.mkdir(parents=True, exist_ok=True)
    #parents = True --> Créé les répertoirs dans le chemin d'accès qui sont nécessaire pour l'enregistrement
    #exist_ok=True --> Si les répertoirs sont déjà existants il n'y aura pas d'erreur

#df_final.to_csv('/Users/bapt/Downloads/World_happiness_Stats.csv')  #Convertir le data set au format CSV